version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MONGO_DB=${MONGO_DB}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - .:/app